name: build-mastr
on: [push]
jobs:
  build-mastr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Install pup
        run: |
          wget --no-verbose https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_*.zip
          chmod +x pup
          sudo mv pup /usr/bin/pup
      - name: Install yj
        run: |
          sudo wget --output-document /usr/bin/yj --no-verbose https://github.com/sclevine/yj/releases/download/v5.0.0/yj-linux
          chmod +x /usr/bin/yj
        # Install a version of sqlite3 that support ".import --skip".
        # https://sqlite.org/forum/forumpost/6ce1a0ae2ade74c1?t=h
        # https://www.sqlite.org/releaselog/3_32_0.html
      - name: Install sqlite3
        run: |
          wget --output-document fossil.tar.gz --no-verbose https://fossil-scm.org/home/uv/fossil-linux-x64-2.17.tar.gz
          tar xvzf fossil.tar.gz
          echo '#!/usr/bin/env bash
          fossil sql --no-repository "$@"' >/usr/bin/sqlite3
          chmod +x /usr/bin/sqlite3
      - name: Install packages
        run: >
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y --no-install-recommends
          axel
          brotli
          libxml2-utils
          osmium-tool
          pv
          ruby-mustache
          spatialite-bin
          sqlite3
      - name: Download raw data
        run: make -C mastr download
      - name: Build database
        run: make -j2 -C mastr Marktstammdatenregister.db.br
