name: Validate export
on:
  schedule:
  - cron: '0 4 * * MON-FRI' # Every weekday at 04:00
  workflow_dispatch:        # Enable manual trigger

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Check out code
      uses: actions/checkout@v2

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Validate
      run: |
        cd mastr
        go build -o validate ./cmd/validate/main.go
        EXPORT_URL="$(curl -sSL https://www.marktstammdatenregister.de/MaStR/Datendownload |
          sed -E 's|^.*(https://download.marktstammdatenregister.de/Gesamtdatenexport_.*\.zip).*$|\1|gp;d')"
        echo "${EXPORT_URL}" | tee result.txt
        curl -sSLo Gesamtdatenexport.zip "${EXPORT_URL}"
        ./validate -export Gesamtdatenexport.zip -spec spec/Gesamtdatenexport.yaml | tee --append result.txt
        curl -sS --header 'x-random;' --upload-file result.txt https://paste.c-net.org/

    - name: E-mail result
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.fastmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Marktstammdatenregister validation result
        to: ~curiousleo/marktstammdatenregister-validation@lists.sr.ht
        from: Marktstammdatenregister validator
        body: file://result.txt
