name: Validate export
on:
  schedule:
  - cron: '0 4 * * *' # Every weekday at 04:00
  workflow_dispatch:  # Enable manual trigger

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        cd mastr
        go build -o validate cmd/validate/main.go
        EXPORT_URL="$(curl -sSL https://www.marktstammdatenregister.de/MaStR/Datendownload |
          sed -E 's|^.*(https://download.marktstammdatenregister.de/Gesamtdatenexport_.*\.zip).*|\1|gp;d')"
        echo "${EXPORT_URL}" | tee report.txt
        curl -sSLo Gesamtdatenexport.zip "${EXPORT_URL}"
        ./validate -export Gesamtdatenexport.zip -spec spec/Gesamtdatenexport.yaml | tee --append report.txt
        curl --upload-file report.txt https://paste.c-net.org/
